/**
 * HTTPステータスコード定数
 * @see https://developer.mozilla.org/ja/docs/Web/HTTP/Status
 */

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  NO_CONTENT: 204,

  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  METHOD_NOT_ALLOWED: 405,
  NOT_ACCEPTABLE: 406,
  CONFLICT: 409,
  GONE: 410,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,

  INTERNAL_SERVER_ERROR: 500,
  NOT_IMPLEMENTED: 501,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
  GATEWAY_TIMEOUT: 504,
} as const;

export type HttpStatusCode = typeof HTTP_STATUS[keyof typeof HTTP_STATUS];

/**
 * ドメインエラー用のステータスコードマッピング
 */
export const DOMAIN_ERROR_STATUS = {
  // リソース関連
  NOT_FOUND: HTTP_STATUS.NOT_FOUND,

  // バリデーション関連
  VALIDATION_ERROR: HTTP_STATUS.BAD_REQUEST,

  // ビジネスルール違反
  BUSINESS_RULE_VIOLATION: HTTP_STATUS.BAD_REQUEST,
  CONFLICT: HTTP_STATUS.CONFLICT,

  // 状態遷移エラー
  INVALID_STATE_TRANSITION: HTTP_STATUS.BAD_REQUEST,

  // 操作エラー
  OPERATION_NOT_ALLOWED: HTTP_STATUS.BAD_REQUEST,
} as const;
